//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.0

pub use super::articles::Entity as Articles;
pub use super::comments::Entity as Comments;
pub use super::notes::Entity as Notes;
pub use super::users::Entity as Users;
